# Generated by Django 4.1.6 on 2023-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="accounts.tag"),
        ),
    ]
